CONNECTION_HOST: hbase
CONNECTION_PORT: 9090

TABLE_NAME: teste_1

COLUMN_FAMILIES:
  - &EVENTOS eventos
  - &INFO_VOO info_voo
  - &POSICAO posicao

DATABASES_INFO:
  # cat62:
  #   SAMPLE_PATH: app/samples/cat62-ita-23jan-31jan.csv
  #   COLUMN_FAMILY_MAP:
  #     *EVENTOS: []
  #     *INFO_VOO: []
  #     *POSICAO: []
  sisceab:
    SAMPLE_PATH: app/samples/sisceab-23jan.csv
    COLUMN_FAMILY_MAP:
      *EVENTOS: []
      *INFO_VOO: ['co_addep', 'co_addes', 'co_indicativo', 'co_modelo', 'dh_inicio', 'dh_fim']
      *POSICAO: []
  tatic:
    SAMPLE_PATH: app/samples/tatic-23jan.csv
    COLUMN_FAMILY_MAP:
      *EVENTOS: ['cpush', 'wpush', 'wtaxi', 'taxi', 'hold', 'crwy', 'cdep', 'dep', 'arr', 'cpos']
      *INFO_VOO: []
      *POSICAO: []
